using Gameplay.Entities;
using Gameplay.Items;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Gameplay.Loot
{
    /// <summary>
    /// Loot item generated by a loot table entry
    /// Loot tables produce a list of these
    /// </summary>
    public class DroppedItem
    {
        public Item_Type Item;
        public int Quantity;
        public int MinLevel;
        public int MaxLevel;

        public bool Eligible(PlayerCharacter pc)
        {
            if (MinLevel > 0)
            {
                if (pc.Stats.FameLevel < MinLevel) return false;
            }
            if (MaxLevel > 0)
            {
                if (pc.Stats.FameLevel > MaxLevel) return false;
            }

            return true;
        }
    }
}
